apiVersion: v1
kind: Service
metadata:
  name: datipubblici
  labels:
    app: datipubblici
spec:
  type: NodePort
  ports:
  - port: 9000
    protocol: TCP
    name: http
  - port: 7000
    protocol: TCP
    name: metrics
  selector:
    app: datipubblici
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: datipubblici-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: datipubblici
        logging: daf_app
    spec:
      containers:
      - name: datipubblici
        image: nexus.teamdigitale.test/daf-datipubblici:2.0.13-SNAPSHOT
        imagePullPolicy: Always
        env:
        - name: JAVA_OPTS
          value: "-server -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+PerfDisableSharedMem -XX:+ParallelRefProcEnabled -Xmx2g -Xms2g -XX:MaxPermSize=1024m"
        - name: PLAY_CRYPTO
          valueFrom:
            secretKeyRef:
              name: daf-secret
              key: play_crypto
        - name: MONGO_USER_PWD
          valueFrom:
            secretKeyRef:
              name: daf-secret
              key: mongo_user_pwd
        - name: PAC4J_CRYPTO
          valueFrom:
            secretKeyRef:
              name: daf-secret
              key: pac4j_crypto
        - name: LDAP_USER_PWD
          valueFrom:
            secretKeyRef:
              name: daf-secret
              key: ldap_user_pwd
        - name: KYLO_USER_PWD
          valueFrom:
            secretKeyRef:
              name: daf-secret
              key: kylo_user_pwd
        - name: SUPERSET_OPEN_DATA_PWD
          valueFrom:
            secretKeyRef:
              name: daf-secret
              key: superset_open_data_pwd
        - name: OPEN_DATA_USER_PWD
          valueFrom:
            secretKeyRef:
              name: daf-secret
              key: open_data_user_pwd
        - name: MONGO_ROOT_PWD
          valueFrom:
            secretKeyRef:
              name: daf-secret
              key: mongo_admin_pwd
        ports:
        - name: client
          containerPort: 9000
        - name: metrics
          containerPort: 7000
        resources:
          limits:
            memory: 2548Mi
        volumeMounts:
        - name: config-volume
          mountPath: /opt/docker/conf/mnt
        - name: datipubblici-logback-volume
          mountPath: /opt/docker/conf/logback.xml
          subPath: logback.xml
        - name: glusterfsvol
          mountPath: /opt/docker/public/img
          subPath: datipubblici/public/img
          readOnly: false
        - name: hosts
          mountPath: /etc/extra_hosts
        - name: krb5conf
          mountPath: /etc/krb5.conf
#        - name: hadoopconf
#          mountPath: /etc/hadoop/conf
#          readOnly: true
      imagePullSecrets:
        - name: regsecret
      volumes:
      - name: config-volume
        configMap:
          name: datipubblici-conf
      - name: datipubblici-logback-volume
        configMap:
          name: datipubblici-logback
      - name: glusterfsvol
        persistentVolumeClaim:
          claimName: gluster-claim
      - name: hosts
        hostPath:
          path: /etc/hosts
      - name: krb5conf
        hostPath:
          path: /etc/krb5.conf
#      - name: hadoopconf
#        hostPath:
#          path: /etc/hadoop/conf
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "nifi"
                  operator: NotIn
                  values: ["true"]
